apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80;http://+:7777
  RabbitMq__Host: rabbit-clusterip
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: Http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip
  # RabbitMq__Username: rabbit
  # RabbitMq__Password: rabbitpw
  # ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip
  # RabbitMq__Username: rabbit
  # RabbitMq__Password: rabbitpw
  # ConnectionStrings__BidDbConnection: mongodb://root:mongopw@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip
  IdentityServiceUrl: http://identity-clusterip
  GrpcAuction: http://auction-clusterip:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip
  # RabbitMq__Username: rabbit
  # RabbitMq__Password: rabbitpw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.carsties.local
  IdentityServiceUrl: http://identity-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.carsties.local
  IssueUri: https://id.carsties.local
  # ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=password;Database=identity
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-svc-config
data:
  # AUTH_SECRET: "YxuFmup97axug3uYco9FoMNYNSdP/T7jI8l+096MIoGpJttXzpdBO1c6Uqs="
  API_URL: http://gateway-clusterip
  ID_URL: https://id.carsties.local
  ID_URL_INTERNAL: http://identity-clusterip
  AUTH_URL: https://app.carsties.local
  AUTH_URL_INTERNAL: http://webapp-clusterip:3000
  NEXT_PUBLIC_NOTIFY_URL: https://api.carsties.local/notifications