apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
spec:
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      labels:
        app: search-svc
    spec:
      containers:
      - name: search-svc
        image: svgengrawuh/search-svc
        imagePullPolicy: Never
        env:
          - name: ConnectionStrings__MongoDbConnection
            valueFrom:
              secretKeyRef:
                name: search-secret
                key: connString
        envFrom:
          - configMapRef:
              name: search-svc-config
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip
spec:
  type: ClusterIP
  selector:
    app: search-svc
  ports:
  - port: 80
    targetPort: 80
    name: web